### ISSUE TITLE
验证存活粗糙

### ISSUE THREAD

**Issue by muddlelife** [AabyssZG/Web-SurvivalScan#6]
个人觉得，只通过request进行发包，去判断url地址是否能访问，略显粗糙，如果可以在发送请求后获得title，server等字段，一方面能验证存活性，另一方面可以根据这些信息，选择出重点资产，毕竟就是发送一个请求包，在代码层面通过response中的数据获得更多的字段不是更好吗

**Comment by AabyssZG** [comment]
感谢师傅的建议，在国庆的时候抽空看了一下
已经在导出的内容中新增title字段的爬取，并在输出的JSON和HTML文件中展示出来
意见已经采纳，版本已经更新完成
