### ISSUE TITLE
输入要检测的文件名之后，文件变为空了

### ISSUE THREAD

**Issue by yuan-boss** [AabyssZG/Web-SurvivalScan#9]
输入文件名，回车，没选择代理，生成的所有文件都是空的，而且源文件也变空了

**Comment by AabyssZG** [comment]
能否提供TXT的相关格式，或者其他相关信息

**Comment by AabyssZG** [comment]
已经私聊解决，如有序有问题，欢迎再提issues
感谢师傅的关注和支持哈哈~😘
